# Generated by Django 2.2.4 on 2019-09-01 07:45

import os
import json
from django.db import migrations, models
import django.db.models.deletion


FILE_NAME = 'data/ingredient-data.json'
FILE_LOCATION = os.path.join(\
    os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir)), \
    FILE_NAME)

def get_json_data(FILE_LOCATION):
    with open(FILE_LOCATION) as f:
        data = json.load(f)
        result = []
        for datum in data:
            result.append(datum)
            if len(result) == 100:
                yield result
                result = []
        yield result

def insert_ingredient(apps, schema_editor):
    Ingredient = apps.get_model('item', 'Ingredient')
    json_data = get_json_data(FILE_LOCATION)
    try:
        if len(json_data) == 0:
            raise Exception

        nutrient_point = {'O': 1, '': 0, 'X': -1}

        for data in json_data:
            ingredient_list = []
            for datum in data:
                datum['oily'] = nutrient_point[datum['oily']]
                datum['dry'] = nutrient_point[datum['dry']]
                datum['sensitive'] = nutrient_point[datum['sensitive']]
                ig = Ingredient(**datum)
                ingredient_list.append(ig)
                print('\n\n ig >>>>> ', ig)
            print('\n\n\n ingredient_list >>>>> ', ingredient_list)
            Ingredient.objects.bulk_create(ingredient_list)
    except Exception as sqlerr:
        print('\n\n insert_ingredient.sqlerr >>>>> ', sqlerr)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.IntegerField(choices=[(0, '구분없음'), (1, '남자'), (2, '여자')])),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('oily', models.IntegerField(choices=[(1, '유익함'), (0, '영향없음'), (-1, '유해함')])),
                ('dry', models.IntegerField(choices=[(1, '유익함'), (0, '영향없음'), (-1, '유해함')])),
                ('sensitive', models.IntegerField(choices=[(1, '유익함'), (0, '영향없음'), (-1, '유해함')])),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=1023)),
                ('name', models.CharField(max_length=1023)),
                ('price', models.IntegerField(default=0)),
                ('monthly_sales', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Category')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Gender')),
                ('ingredients', models.ManyToManyField(to='item.Ingredient')),
            ],
        ),
        migrations.RunPython(insert_ingredient),
    ]
